distribution-map: &distribution-map
  type: EXPRESSION
  expression: split((noise(x/spread,z/spread)+1)*4/(radius/spread)-1)
  variables:
    spread: 35
    radius: 10
  functions:
    split:
      arguments: [x]
      expression: if(x<1,x,1)
  samplers:
    noise:
      dimensions: 2
      type: DOMAIN_WARP
      amplitude: 0.01
      warp:
        type: OPEN_SIMPLEX_2
        salt: 3912
        frequency: 10
      sampler:
        type: CELLULAR
        salt: 5912
        frequency: 1
        return: Distance2Div

stages:
  - type: REPLACE
    sampler: *distribution-map
    from: outer_end
    to:
      - aether: 32
      - STARFIELD: 28
      - end: 36
  - type: REPLACE_LIST
    sampler:
      dimensions: 2
      type: LINEAR
      min: -1
      max: -0.65
      sampler:
        type: FBM
        lacunarity: 3
        gain: 0.4
        octaves: 4
        sampler:
          type: CELLULAR
          frequency: 1 / ${meta.yml:biome-distribution.continental-scale} / ${meta.yml:biome-distribution.global-scale}
    default-from: end
    default-to:
      - end: 2
      - shattered_end: 1
      - void: 3
    to:
      aether:
        - aether: 2
        - aether_highlands: 1
